from kaizen.core.models import Message, Role, ToolCall


def test_toolcall_has_autogenerated_id():
    a, b = ToolCall(name="x"), ToolCall(name="x")
    assert a.id and b.id and a.id != b.id


def test_message_tool_call_id_defaults_none():
    assert Message(role=Role.USER, content="hi").tool_call_id is None
